export const results = [
  {
    id: 'MLA709580097',
    site_id: 'MLA',
    title: 'Banquetas Taburete Alta Con Respaldo En Hierro Pino Macizo',
    seller: {},
    price: 2490,
    prices: {},
    sale_price: null,
    currency_id: 'ARS',
    available_quantity: 5000,
    sold_quantity: 500,
    buying_mode: 'buy_it_now',
    listing_type_id: 'gold_special',
    stop_time: '2038-02-19T04:00:00.000Z',
    condition: 'new',
    permalink:
      'https://articulo.mercadolibre.com.ar/MLA-709580097-banquetas-taburete-alta-con-respaldo-en-hierro-pino-macizo-_JM',
    thumbnail: 'http://http2.mlstatic.com/D_752347-MLA43783763994_102020-I.jpg',
    accepts_mercadopago: true,
    installments: {},
    address: {},
    shipping: {},
    seller_address: {},
    attributes: [],
    original_price: null,
    category_id: 'MLA6656',
    official_store_id: null,
    domain_id: 'MLA-STOOLS',
    catalog_product_id: null,
    tags: [],
    order_backend: 1
  },
  {
    id: 'MLA828145399',
    site_id: 'MLA',
    title: 'Banco Taburete Silla De Pino Natural 75cm Alto',
    seller: {},
    price: 1638.75,
    prices: {},
    sale_price: null,
    currency_id: 'ARS',
    available_quantity: 5000,
    sold_quantity: 500,
    buying_mode: 'buy_it_now',
    listing_type_id: 'gold_special',
    stop_time: '2039-11-25T04:00:00.000Z',
    condition: 'new',
    permalink:
      'https://articulo.mercadolibre.com.ar/MLA-828145399-banco-taburete-silla-de-pino-natural-75cm-alto-_JM',
    thumbnail: 'http://http2.mlstatic.com/D_702007-MLA43783830157_102020-I.jpg',
    accepts_mercadopago: true,
    installments: {},
    address: {},
    shipping: {},
    seller_address: {},
    attributes: [],
    original_price: 1725,
    category_id: 'MLA6656',
    official_store_id: null,
    domain_id: 'MLA-STOOLS',
    catalog_product_id: null,
    tags: [],
    order_backend: 2
  },
  {
    id: 'MLA836747732',
    site_id: 'MLA',
    title: 'Banco Taburete Silla De Pino Natural 45cm Alto',
    seller: {},
    price: 1149.5,
    prices: {},
    sale_price: null,
    currency_id: 'ARS',
    available_quantity: 500,
    sold_quantity: 200,
    buying_mode: 'buy_it_now',
    listing_type_id: 'gold_special',
    stop_time: '2040-01-24T04:00:00.000Z',
    condition: 'new',
    permalink:
      'https://articulo.mercadolibre.com.ar/MLA-836747732-banco-taburete-silla-de-pino-natural-45cm-alto-_JM',
    thumbnail: 'http://http2.mlstatic.com/D_760825-MLA43784031544_102020-I.jpg',
    accepts_mercadopago: true,
    installments: {},
    address: {},
    shipping: {},
    seller_address: {},
    attributes: [],
    original_price: null,
    category_id: 'MLA6656',
    official_store_id: null,
    domain_id: 'MLA-STOOLS',
    catalog_product_id: null,
    tags: [],
    order_backend: 3
  },
  {
    id: 'MLA737567562',
    site_id: 'MLA',
    title: 'Banquito Banco Taburete Sillita Silla De Pino Natural',
    seller: {},
    price: 978,
    prices: {},
    sale_price: null,
    currency_id: 'ARS',
    available_quantity: 500,
    sold_quantity: 250,
    buying_mode: 'buy_it_now',
    listing_type_id: 'gold_special',
    stop_time: '2038-07-11T04:00:00.000Z',
    condition: 'new',
    permalink:
      'https://articulo.mercadolibre.com.ar/MLA-737567562-banquito-banco-taburete-sillita-silla-de-pino-natural-_JM',
    thumbnail: 'http://http2.mlstatic.com/D_961095-MLA43783833798_102020-O.jpg',
    accepts_mercadopago: true,
    installments: {},
    address: {},
    shipping: {},
    seller_address: {},
    attributes: [],
    original_price: null,
    category_id: 'MLA6656',
    official_store_id: null,
    domain_id: 'MLA-STOOLS',
    catalog_product_id: null,
    tags: [],
    order_backend: 4
  }
];
