export const results = [
  {
    id: 'MLA638356862',
    site_id: 'MLA',
    title: 'Cartucho Hp 122 Negro Original Deskjet 1000 2050 3000 3050',
    seller: {},
    price: 1520,
    prices: {},
    sale_price: null,
    currency_id: 'ARS',
    available_quantity: 50,
    sold_quantity: 500,
    buying_mode: 'buy_it_now',
    listing_type_id: 'gold_special',
    stop_time: '2038-01-02T03:26:25.000Z',
    condition: 'new',
    permalink:
      'https://articulo.mercadolibre.com.ar/MLA-638356862-cartucho-hp-122-negro-original-deskjet-1000-2050-3000-3050-_JM',
    thumbnail: 'http://http2.mlstatic.com/D_703097-MLA31036711653_062019-I.jpg',
    accepts_mercadopago: true,
    installments: {},
    address: {
      state_id: 'AR-C',
      state_name: 'Capital Federal',
      city_id: 'TUxBQlZJTDI3MDJa',
      city_name: 'Villa Luro'
    },
    shipping: {
      free_shipping: false,
      mode: 'me2',
      tags: [],
      logistic_type: 'fulfillment',
      store_pick_up: false
    },
    seller_address: {},
    attributes: [],
    original_price: null,
    category_id: 'MLA7415',
    official_store_id: null,
    domain_id: 'MLA-INK_CARTRIDGES',
    catalog_product_id: 'MLA6076515',
    tags: [],
    order_backend: 1
  },
  {
    id: 'MLA614572161',
    site_id: 'MLA',
    title: 'Combo De Cartuchos Hp 122 Negro + Color 3050 2050 Original',
    seller: {},
    price: 3550,
    prices: {},
    sale_price: null,
    currency_id: 'ARS',
    available_quantity: 1,
    sold_quantity: 500,
    buying_mode: 'buy_it_now',
    listing_type_id: 'gold_special',
    stop_time: '2036-03-25T14:15:36.000Z',
    condition: 'new',
    permalink:
      'https://articulo.mercadolibre.com.ar/MLA-614572161-combo-de-cartuchos-hp-122-negro-color-3050-2050-original-_JM',
    thumbnail: 'http://http2.mlstatic.com/D_804530-MLA31009028024_062019-I.jpg',
    accepts_mercadopago: true,
    installments: {},
    address: {
      state_id: 'AR-C',
      state_name: 'Capital Federal',
      city_id: 'TUxBQlZJTDI3MDJa',
      city_name: 'Villa Luro'
    },
    shipping: {
      free_shipping: true,
      mode: 'me2',
      tags: [],
      logistic_type: 'fulfillment',
      store_pick_up: false
    },
    seller_address: {},
    attributes: [],
    original_price: null,
    category_id: 'MLA7415',
    official_store_id: null,
    domain_id: 'MLA-INK_CARTRIDGES',
    catalog_product_id: null,
    tags: [],
    order_backend: 2
  },
  {
    id: 'MLA682718644',
    site_id: 'MLA',
    title: 'Cartucho Alternativo Para 122xl Negro 3050 2050 3052 3054',
    seller: {},
    price: 1545,
    prices: {},
    sale_price: null,
    currency_id: 'ARS',
    available_quantity: 150,
    sold_quantity: 500,
    buying_mode: 'buy_it_now',
    listing_type_id: 'gold_special',
    stop_time: '2037-09-06T23:34:35.000Z',
    condition: 'new',
    permalink:
      'https://articulo.mercadolibre.com.ar/MLA-682718644-cartucho-alternativo-para-122xl-negro-3050-2050-3052-3054-_JM',
    thumbnail: 'http://http2.mlstatic.com/D_893192-MLA31017735831_062019-I.jpg',
    accepts_mercadopago: true,
    installments: {},
    address: {
      state_id: 'AR-C',
      state_name: 'Capital Federal',
      city_id: 'TUxBQkJBUjM0MDha',
      city_name: 'Barracas'
    },
    shipping: {
      free_shipping: false,
      mode: 'me2',
      tags: [],
      logistic_type: 'cross_docking',
      store_pick_up: false
    },
    seller_address: {},
    attributes: [],
    original_price: null,
    category_id: 'MLA7415',
    official_store_id: null,
    domain_id: 'MLA-INK_CARTRIDGES',
    catalog_product_id: null,
    tags: [],
    order_backend: 3
  },
  {
    id: 'MLA874929802',
    site_id: 'MLA',
    title: 'Combo Cartucho Hp 122 Negro + Color 1000 2000 3000 3050',
    seller: {},
    price: 3545,
    prices: {},
    sale_price: null,
    currency_id: 'ARS',
    available_quantity: 1,
    sold_quantity: 250,
    buying_mode: 'buy_it_now',
    listing_type_id: 'gold_special',
    stop_time: '2040-08-19T04:00:00.000Z',
    condition: 'new',
    permalink:
      'https://articulo.mercadolibre.com.ar/MLA-874929802-combo-cartucho-hp-122-negro-color-1000-2000-3000-3050-_JM',
    thumbnail: 'http://http2.mlstatic.com/D_652969-MLA43250164083_082020-I.jpg',
    accepts_mercadopago: true,
    installments: {},
    address: {
      state_id: 'AR-C',
      state_name: 'Capital Federal',
      city_id: 'TUxBQlBBVDI0ODFa',
      city_name: 'Paternal'
    },
    shipping: {
      free_shipping: true,
      mode: 'me2',
      tags: [],
      logistic_type: 'cross_docking',
      store_pick_up: false
    },
    seller_address: {},
    attributes: [],
    original_price: null,
    category_id: 'MLA7415',
    official_store_id: null,
    domain_id: 'MLA-INK_CARTRIDGES',
    catalog_product_id: 'MLA6076514',
    tags: [],
    order_backend: 4
  }
];
